### ISSUE TITLE
Passar os agricultores de uma OCS, quando for a editar

### ISSUE THREAD

**Issue by Dev-Henrique-Almeida** [lmtsufape/assim-gestao-web#17]
Ao criar uma OCS, ela não salva os agricultores que foram integrados a ela, logo quando vai editar, acaba não passando eles:

![image](https://github.com/lmtsufape/assim-gestao-web/assets/101284170/a888ee5a-7649-48b6-be4d-209b5259aaae)

**Comment by jvictorcordeiro** [comment]
Agricultores são salvos, porém não retornam no index de cada OCS
